name: "Validate RFC XML and Generate Drafts"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: "Validate and Generate Drafts"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v3

    - name: "Setup Python"
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: "Install xml2rfc"
      run: pip install xml2rfc

    - name: "Validate RFC XML"
      run: |
        xml2rfc --parse draft-hip-human-identity-protocol-00.xml

    - name: "Generate RFC TXT"
      run: |
        xml2rfc --text draft-hip-human-identity-protocol-00.xml

    - name: "Generate RFC HTML"
      run: |
        xml2rfc --html draft-hip-human-identity-protocol-00.xml
